image: Visual Studio 2019

environment:
  matrix:
  - solution_path: sem4\LambdaInterpreter\LambdaInterpreter.sln
  - solution_path: sem4\LocalNetwork\LocalNetwork.sln
  - solution_path: sem4\LazyAdvanced\LazyAdvanced.sln
  - solution_path: sem4\WebDownloader\WebDownloader.sln
  - solution_path: sem4\Factorial\Factorial.sln
  - solution_path: sem4\CalculateBuilder\CalculateBuilder.sln
  - solution_path: sem4/EvenNumbers/EvenNumbers.sln
  - solution_path: sem4/ParseTree/ParseTree.sln
  - solution_path: sem4/MapForTrees/MapForTrees.sln
  - solution_path: sem4\InfinitePrimes\InfinitePrimes.sln
  - solution_path: sem4\BracketsChecker\BracketsChecker.sln
  - solution_path: sem4/Pointfree/Pointfree.sln
  - solution_path: sem4\PhoneBook\PhoneBook.sln
  - solution_path: sem4\SpecifiedAccuracy\SpecifiedAccuracy.sln
  - solution_path: Tests\Task1\Task1.sln

before_build:
  - nuget restore sem4\LambdaInterpreter\LambdaInterpreter.sln
  - nuget restore sem4\LocalNetwork\LocalNetwork.sln
  - nuget restore sem4\LazyAdvanced\LazyAdvanced.sln
  - nuget restore sem4\WebDownloader\WebDownloader.sln
  - nuget restore sem4\Factorial\Factorial.sln
  - nuget restore sem4\CalculateBuilder\CalculateBuilder.sln
  - nuget restore sem4/EvenNumbers/EvenNumbers.sln
  - nuget restore sem4/ParseTree/ParseTree.sln
  - nuget restore sem4/MapForTrees/MapForTrees.sln
  - nuget restore sem4\InfinitePrimes\InfinitePrimes.sln
  - nuget restore sem4\BracketsChecker\BracketsChecker.sln
  - nuget restore sem4/Pointfree/Pointfree.sln
  - nuget restore sem4\PhoneBook\PhoneBook.sln
  - nuget restore sem4\SpecifiedAccuracy\SpecifiedAccuracy.sln
  - nuget restore Tests\Task1\Task1.sln

build_script:
  - nuget restore %solution_path%
  - msbuild %solution_path%
  - ps: |
      $solutionDir = Split-Path "$env:solution_path"
      Write-Host "Looking for test projects inside $solutionDir"
      $testProjects = Get-ChildItem -Recurse -Path $solutionDir -Filter *.Tests.fsproj -ErrorAction SilentlyContinue
      if ($testProjects.Count -eq 0) {
        Write-Host "No test projects found inside $solutionDir"
      } else {
        foreach ($proj in $testProjects) {
          Write-Host "Running tests from $($proj.FullName)"
          dotnet test $proj.FullName
        }
      }

