image: Visual Studio 2019

environment:
  matrix:
  - solution_path: sem4\LambdaInterpreter\LambdaInterpreter.sln
  - solution_path: sem4\LocalNetwork\LocalNetwork.sln
  - solution_path: sem4\LazyAdvanced\LazyAdvanced.sln
  - solution_path: sem4\WebDownloader\WebDownloader.sln
  - solution_path: sem4\Factorial\Factorial.sln
  - solution_path: sem4\CalculateBuilder\CalculateBuilder.sln
  - solution_path: sem4/EvenNumbers/EvenNumbers.sln
  - solution_path: sem4/ParseTree/ParseTree.sln
  - solution_path: sem4/MapForTrees/MapForTrees.sln
  - solution_path: sem4\InfinitePrimes\InfinitePrimes.sln
  - solution_path: sem4\BracketsChecker\BracketsChecker.sln
  - solution_path: sem4/Pointfree/Pointfree.sln
  - solution_path: sem4\PhoneBook\PhoneBook.sln
  - solution_path: sem4\SpecifiedAccuracy\SpecifiedAccuracy.sln
  - solution_path: Tests\Task1\Task1.sln

before_build:
  - nuget restore sem4\LambdaInterpreter\LambdaInterpreter.sln
  - nuget restore sem4\LocalNetwork\LocalNetwork.sln
  - nuget restore sem4\LazyAdvanced\LazyAdvanced.sln
  - nuget restore sem4\WebDownloader\WebDownloader.sln
  - nuget restore sem4\Factorial\Factorial.sln
  - nuget restore sem4\CalculateBuilder\CalculateBuilder.sln
  - nuget restore sem4/EvenNumbers/EvenNumbers.sln
  - nuget restore sem4/ParseTree/ParseTree.sln
  - nuget restore sem4/MapForTrees/MapForTrees.sln
  - nuget restore sem4\InfinitePrimes\InfinitePrimes.sln
  - nuget restore sem4\BracketsChecker\BracketsChecker.sln
  - nuget restore sem4/Pointfree/Pointfree.sln
  - nuget restore sem4\PhoneBook\PhoneBook.sln
  - nuget restore sem4\SpecifiedAccuracy\SpecifiedAccuracy.sln
  - nuget restore Tests\Task1\Task1.sln

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test sem4\LambdaInterpreter\LambdaInterpreter\LambdaInterpreter.Tests.fsproj
  - dotnet test sem4\LocalNetwork\LocalNetwork\LocalNetwork.Tests.fsproj
  - dotnet test sem4\LazyAdvanced\LazyAdvanced\LazyAdvanced.Tests.fsproj
  - dotnet test sem4\WebDownloader\WebDownloader\WebDownloader.Tests.fsproj
  - dotnet test sem4\Factorial\Factorial.Tests\Factorial.Tests.fsproj
  - dotnet test sem4\CalculateBuilder\CalculateBuilder.Tests\CalculateBuilder.Tests.fsproj
  - dotnet test sem4\EvenNumbers\EvenNumbers.Tests\EvenNumbers.Tests.fsproj
  - dotnet test sem4\ParseTree\ParseTree.Tests\ParseTree.Tests.fsproj
  - dotnet test sem4\MapForTrees\MapForTrees.Tests\MapForTrees.Tests.fsproj
  - dotnet test sem4\InfinitePrimes\InfinitePrimes\InfinitePrimes.fsproj
  - dotnet test sem4\BracketsChecker\BracketsChecker.Tests\BracketsChecker.Tests.fsproj
  - dotnet test sem4\Pointfree\Pointfree.Tests\Pointfree.Tests.fsproj
  - dotnet test sem4\PhoneBook\PhoneBook\PhoneBook.fsproj
  - dotnet test sem4\SpecifiedAccuracy\SpecifiedAccuracyTests\SpecifiedAccuracy.Tests.fsproj
  - dotnet test Tests\Task1\Task1\Task1.fsproj
